### ISSUE TITLE
Pre-built Knowledge Base Packs

### ISSUE THREAD

**Issue by cookersjs** [oicr-ibc/heliotrope#71]
Hi @morungos, hope things are well!

Im currently plodding through the perl files in heliotrope/bin, trying to get them functional. In the readme you mention that using a pre-built knowledge base pack would make it easier to get the process going. The link for the pre-built packs is dead and I have two questions as a result:

1) I am trying to initialize the knowledge base just by running 'bash build.sh', interpreting the error messages, solving them, and repeating. Is there any other arguments I need aside from 'bash build.sh' when doing this?

2) Do the pre-built packs still exist and if they do, can I access them?

None of this is urgent but I figured I would post it so that when you do have time you would know what questions I have.

All the best!

**Comment by morungos** [comment]
Hmm, yes, I think it was on dropbox at some time, but I can't find it there now, and there's no obvious archive. I'll keep looking

**Comment by morungos** [comment]
OK, just found the backups for these. I'll put them somewhere you can download them

**Comment by morungos** [comment]
URL should be: https://dl.dropboxusercontent.com/u/51478659/heliotrope-dump-1.3.tar.bz2

**Comment by cookersjs** [comment]
Awesome,  I'll check it out tomorrow 

Thanks
